sudo: required
language: cpp
services:
  - docker

script:
  - docker pull $TARGET
  - docker run -e 'MAKEFLAGS=-j2' -v "$TRAVIS_BUILD_DIR:/usr/src/libral" $TARGET /bin/bash /usr/src/libral/contrib/docker/scripts/build.sh

env:
  matrix:
    - TARGET=libral/f25-build
    - TARGET=libral/el6-build-static

notifications:
  email: false
